### ISSUE TITLE
Bug with a test plugin under v1.1.0

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/ipm#15]
My build of v1.1.0 failed with:

```
/scratch/workdir3/sourcecode/ipm/test/plugins/VectorIntIPMSubscriberDAQModule.hpp:19:10: fatal error: ipm/vectorintipmreceiverdaqmodule/Structs.hpp: No such file or directory
 #include "ipm/vectorintipmreceiverdaqmodule/Structs.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Looks like the header file Structs.hpp is not generated in this version.

**Comment by philiprodrigues** [comment]
Sigh, I had the same problem, but assumed it was a transient problem (I had another setting set incorrectly the first time I ran the build) because when I then ran `dbt-build --clean`, everything worked. So I assume the problem is that the file in question is created _in the source tree_ the first time the build is run, but the C++ files that use it don't depend on it, as far as CMake knows. So CMake tries to build the C++ and fails (while, in parallel, creating the `Structs.hpp`). On the second run, even with `--clean`, the `Structs.hpp` _does_ exist, and so the build succeeds. I will take a proper look tomorrow if no one gets there before me

**Comment by dingp** [comment]
Thanks Phil. My first test was in a plain docker container which failed with the above error.

However, my other tries succeeded on SL7 host nodes. Anyhow, this is not an urgent issue as I have built the version and packaged it in UPS and deployed as part of the `dunedaq-v2.2.0` release.

**Comment by jcfreeman2** [comment]
The (current) way to fix this is to add the following:
```
add_dependencies(ipm_VectorIntIPMSubscriberDAQModule_duneDAQModule ipm_VectorIntIPMReceiverDAQModule_duneDAQModule)
```
